import pandas as pd
import torch
import torch.nn.functional as F
from torch_geometric.data import Data 
from torch_geometric.nn import GCNConv
from sklearn.metrics import classification_report


df_features = pd.read_csv("elliptic_txs_features.csv", header =None)
df_features.rename(columns={0:'txId', 1:'time_step'}, inplace=True)

df_classes = pd.read_csv("elliptic_txs_classes.csv")
df_edge = pd.read_csv("elliptic_txs_edgelist.csv")

# 2. Extraer todos los IDs únicos de las características
nodos_unicos = df_features['txId'].unique()

print(f"Всего найдено узлов {len(nodos_unicos)}")

# 3. Crear el diccionario de mapeo {ID_Original : Nuevo_Indice_PyTorch}
# La función 'enumerate' cuenta automáticamente 0, 1, 2, 3...#
#Создать отображение реалного идентификатора
node_to_idx = { node_id:index for index, node_id in enumerate(nodos_unicos)}
print("\n Validation - sample of dictionary")

muestra = {k:node_to_idx[k] for k in list(node_to_idx)[:5]}
for real, pytorch in muestra.items():
    print(f"ID Real:{real} --> Indice IA: {pytorch}")

df_edge['txId1'] = df_edge['txId1'].map(node_to_idx)
df_edge['txId2'] = df_edge['txId2'].map(node_to_idx)
df_edge = df_edge.dropna() #Se actualiza la variable asi misma usando dropna
                            #Si encuentra un espacio vacio(NaN). provocado por un ID que esta en el diccionario
                            #borra esa fila completa

#6. Unir caracteristicas y clases
df_nodos = pd.merge(df_features, df_classes, on="txId", how="left")

# 7 Translate the text classes into mathematics
class_mapping = {'1': 1, '2':0, 'unknown': 2}
df_nodos['class'] = df_nodos['class'].astype(str).map(class_mapping)

#8 tensor
x_features = df_nodos.drop(columns=['txId', 'time_step', 'class']).values
x_tensor = torch.tensor(x_features, dtype=torch.float)

y_tensor = torch.tensor(df_nodos['class'].values, dtype=torch.long)

edge_index_tensor = torch.tensor(df_edge[['txId1', 'txId2']].values, dtype=torch.long).t().contiguous()

graph_data = Data(x=x_tensor, edge_index=edge_index_tensor, y=y_tensor)
print("\n--- RESULTADO FINAL: EL GRAFO VECTORIZADO ---")
print(graph_data)  

class AMLDetectorGCN(torch.nn.Module): #we created a class
    def __init__(self, num_features,num_classes): #this is the constructor/это конструктор
                                                #It initializes the brain structure when we created the model
                                                #Он инициализирует структуру мозга, когда мы создавали модель

        super(AMLDetectorGCN, self).__init__()
        self.conv1 = GCNConv(num_features, 64)
        self.conv2 = GCNConv(64, num_classes)

    def forward(self, x, edge_index):

        x=self.conv1(x, edge_index) # X is updated to the result of passing the features and the topology (EDGE_INDEX) through the first layer. Here, the transactions "talk" to each other.
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        return  F.log_softmax(x, dim=1)
    
    # Preparing the tools
model = AMLDetectorGCN(num_features=165, num_classes=2)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.NLLLoss()

    #3. Applying the train Mask (Ignore Class 2)
train_mask = graph_data.y !=2
print("Starting 100 epochs of training. Watch the loss go down...")
model.train()

for epoch in range(1, 101):
    optimizer.zero_grad() 
    
    out = model(graph_data.x, graph_data.edge_index)
    
    loss = criterion(out[train_mask], graph_data.y[train_mask])
    
    loss.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        print(f'Epoch: {epoch:03d} | Loss (Mathematical Error): {loss.item():.4f}')

print("Training finished successfully!")

print("\n--- STEP 4: MODEL EVALUATION ---")

model.eval()
with torch.no_grad(): #We open a context manager that tells PyTorch: "Do not calculate gradients (math derivatives) right now
                    #This saves a massive amount of RAM and processing power because we are no longer learning, just predicting
    out = model(graph_data.x, graph_data.edge_index)# The variable out is equal to the final probabilities generated by our fully trained brain using the graph features and topology.
    _, predicted_classes = out.max(dim=1)#The variable predicted_classes is equal to the exact category the AI chose. out.max(dim=1) looks at the probabilities for Licit vs Illicit and picks the one with the highest percentage.
    known_mask = graph_data.y != 2#is equal to our filter. We only want to grade the AI like a student on the questions where we actually have the answer key
    y_true = graph_data.y[known_mask].numpy()
    y_pred = predicted_classes[known_mask].numpy()
    print(classification_report(y_true, y_pred, target_names=['Licit (0)', 'Illicit (1)']))


print("\n--- STEP 5: EXPORTING THE BRAIN ---")

# 1. Define the file name (extension .pth is standard for PyTorch)
model_path = "aml_gcn_model.pth"

# 2. Extract the weights (state_dict) and save them to the hard drive
torch.save(model.state_dict(), model_path)

print(f"Success!  to: {model_path}")

print("\n--- STEP 5: EXPORTING THE BRAIN ---")

# 1. Define the file name (extension .pth is standard for PyTorch)
model_path = "aml_gcn_model.pth"

# 2. Extract the weights (state_dict) and save them to the hard drive
torch.save(model.state_dict(), model_path)

print(f"Success! The AI's brain has been exported to: {model_path}")
print("You can now close VS Code without losing what the model learned.")